name: File Read-Edit Jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    concurrency:
      group: concur-job-group
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Read and Edit File
        run: |
          # Reading the file
          cat ${{ github.workspace }}/file.txt

          # Editing the file
          echo "Job 1 editing file" >> ${{ github.workspace }}/file.txt

  job2:
    runs-on: ubuntu-latest
    concurrency:
      group: concur-job-group
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Read and Edit File
        run: |
          # Reading the file
          cat ${{ github.workspace }}/file.txt

          # Editing the file
          echo "Job 2 editing file" >> ${{ github.workspace }}/file.txt

  job3:
    runs-on: ubuntu-latest
    concurrency:
      group: concur-job-group
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Read and Edit File
        run: |
          # Reading the file
          cat ${{ github.workspace }}/file.txt

          # Editing the file
          echo "Job 3 editing file" >> ${{ github.workspace }}/file.txt
